services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - hdv_node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      NODE_ENV: development
    stdin_open: true
    tty: true

volumes:
  hdv_node_modules:
